#!/usr/bin/env python3
"""Statement coverage for the test suite, without a third-party dependency.

The project ships no dependencies and its build environment has no package
index, so ``coverage.py`` is not available. This is a deliberately small
replacement that measures the one thing the thresholds are about: which
statements of ``src/noetrail`` the suite executes.

Method
------
Statements come from ``code.co_lines()`` on the compiled module, walked
recursively through nested code objects. That is the same source of truth the
interpreter uses to report line events, so a statement can never be counted as
missing because the tracer and the statement list disagree.

Execution is recorded with ``sys.settrace``. The global trace function returns
``None`` for every frame outside the measured tree, so uninteresting code pays
one call event and no line events.

Subprocesses
------------
Measuring only the process that runs ``unittest`` would be badly wrong here:
most of the suite drives the CLI and both MCP servers as separate processes
(``tests/__init__.py`` builds ``CLI_COMMAND`` from ``sys.executable``). The
tracer is therefore installed through a generated ``sitecustomize`` module on
``PYTHONPATH``, which every child interpreter imports during startup, and each
process writes its own partial measurement at exit. The parts are merged here.

``threading.settrace`` is set as well, because the bookmark fetcher's HTTP
server and the locking tests do their work on non-main threads, whose frames
the main thread's trace function never sees.

Output
------
A per-module table and, with ``--json``, a machine-readable report. Thresholds
are checked at the end; falling short exits non-zero.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import sysconfig
import tempfile

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = REPOSITORY_ROOT / "src" / "noetrail"
DEFAULT_COMMAND = [
    sys.executable,
    "-m",
    "unittest",
    "discover",
    "-s",
    "tests",
    "-t",
    ".",
]

# Overall floor, plus modules that are small and central enough that a gap in
# them is a real hole rather than an untested corner of a large command surface.
DEFAULT_TOTAL_THRESHOLD = 80.0
MODULE_THRESHOLDS = {
    "migrations.py": 95.0,
    "layout.py": 95.0,
    "jsonrpc.py": 95.0,
    # A parser whose whole job is to refuse. Its accepting half is a handful
    # of assignments; everything else in it is a `raise` that only means
    # something if it has been shown to fire.
    "views.py": 95.0,
}

# The SSRF guard is spread over one file that also contains HTML parsing and a
# JSON-RPC server, so a file-level threshold would say nothing about it. These
# are the definitions that decide where a fetch is allowed to connect and which
# redirects it follows; they are sliced out by name and scored on their own.
SSRF_SLICE = {
    "file": "bookmark_fetcher.py",
    "label": "bookmark_fetcher.py (SSRF path)",
    "threshold": 95.0,
    "definitions": [
        "normalize_url",
        "is_public_address",
        "resolve_targets",
        "DestinationGuard",
        "public_url",
        "release_response",
        "PinnedConnectionMixin",
        "PinnedHTTPConnection",
        "PinnedHTTPSConnection",
        "PinnedHTTPHandler",
        "PinnedHTTPSHandler",
        "SafeRedirectHandler",
    ],
}

SITECUSTOMIZE = '''\
"""Generated by tools/coverage.py -- installs the tracer in every process."""

import atexit
import json
import os
from pathlib import Path
import sys
import threading

_DATA = os.environ.get("NOETRAIL_COVERAGE_DATA")
_SOURCE = os.environ.get("NOETRAIL_COVERAGE_SOURCE")

if _DATA and _SOURCE:
    _source_root = str(Path(_SOURCE).resolve())
    # Keyed by resolved path, so two spellings of the same file merge.
    _executed = {}
    # Keyed by the raw ``co_filename``, which is what the hot path sees.
    _sets = {}
    _rejected = set()

    def _line_trace(frame, event, arg):
        if event == "line":
            target = _sets.get(frame.f_code.co_filename)
            if target is not None:
                target.add(frame.f_lineno)
        return _line_trace

    def _call_trace(frame, event, arg):
        # Returning None for a frame switches off line events for it, so code
        # outside the measured tree costs one call event and nothing more.
        if event != "call":
            return None
        filename = frame.f_code.co_filename
        if filename in _sets:
            return _line_trace
        if filename in _rejected:
            return None
        try:
            resolved = str(Path(filename).resolve())
        except OSError:
            resolved = filename
        if resolved.startswith(_source_root + os.sep):
            _sets[filename] = _executed.setdefault(resolved, set())
            return _line_trace
        _rejected.add(filename)
        return None

    def _dump():
        sys.settrace(None)
        threading.settrace(None)
        payload = {name: sorted(lines) for name, lines in _executed.items()}
        if not payload:
            return
        target = Path(_DATA) / f"part-{os.getpid()}-{id(payload):x}.json"
        try:
            target.write_text(json.dumps(payload), encoding="utf-8")
        except OSError:
            pass

    atexit.register(_dump)
    threading.settrace(_call_trace)
    sys.settrace(_call_trace)
'''


PRAGMA = "pragma: no cover"


def excluded_lines(source: str, path: Path) -> set[int]:
    """Return the lines a ``# pragma: no cover`` marker takes out of scope.

    A marker on a statement that opens a block -- a function, an ``if``, an
    ``except`` clause -- excludes the whole block, because that is what the
    comment means. Anything else excludes only its own line.
    """

    marked = {
        number
        for number, line in enumerate(source.splitlines(), 1)
        if PRAGMA in line
    }
    if not marked:
        return set()

    excluded = set(marked)
    for node in ast.walk(ast.parse(source, filename=str(path))):
        start = getattr(node, "lineno", None)
        end = getattr(node, "end_lineno", None)
        if start in marked and end is not None:
            excluded.update(range(start, end + 1))
    return excluded


def statements_of(path: Path) -> set[int]:
    """Return executable source lines, consistently across Python releases.

    Python 3.14 implements deferred annotations with compiler-generated
    ``__annotate__`` code objects. Their line tables point at function
    signatures, but normal execution never calls them, so counting them made
    identical source appear less covered on 3.14 than on 3.13. Multiline
    signature continuation lines are metadata rather than executable
    statements as well; remove them from every version's result.
    """

    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    code = compile(source, str(path), "exec")
    lines: set[int] = set()
    pending = [code]
    while pending:
        current = pending.pop()
        for _, _, lineno in current.co_lines():
            if lineno is not None and lineno > 0:
                lines.add(lineno)
        pending.extend(
            const
            for const in current.co_consts
            if hasattr(const, "co_lines") and const.co_name != "__annotate__"
        )

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        if not node.body:
            continue
        first_body_line = node.body[0].lineno
        lines.difference_update(range(node.lineno + 1, first_body_line))
    return lines - excluded_lines(source, path)


def definition_ranges(path: Path, names: list[str]) -> set[int]:
    """Return the line span of the named top-level definitions."""

    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    wanted = set(names)
    covered: set[int] = set()
    found: set[str] = set()
    for node in tree.body:
        if not isinstance(
            node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef
        ):
            continue
        if node.name not in wanted:
            continue
        found.add(node.name)
        end = node.end_lineno or node.lineno
        covered.update(range(node.lineno, end + 1))
    missing = sorted(wanted - found)
    if missing:
        # A renamed or deleted function must not quietly shrink the slice the
        # threshold is measured over.
        raise SystemExit(
            f"{path.name}: coverage slice names unknown definitions: "
            f"{', '.join(missing)}"
        )
    return covered


def run_measured(
    command: list[str],
    source: Path,
    data_directory: Path,
) -> int:
    """Run the command with the tracer installed in it and its children."""

    with tempfile.TemporaryDirectory(prefix="noetrail-coverage-") as booter:
        (Path(booter) / "sitecustomize.py").write_text(
            SITECUSTOMIZE,
            encoding="utf-8",
        )
        environment = dict(os.environ)
        inherited = environment.get("PYTHONPATH", "")
        parts = [booter, str(source.parent)]
        if inherited:
            parts.append(inherited)
        environment["PYTHONPATH"] = os.pathsep.join(parts)
        environment["NOETRAIL_COVERAGE_DATA"] = str(data_directory)
        environment["NOETRAIL_COVERAGE_SOURCE"] = str(source)
        return subprocess.run(
            command,
            env=environment,
            cwd=REPOSITORY_ROOT,
            check=False,
        ).returncode


def merge_parts(data_directory: Path) -> dict[str, set[int]]:
    merged: dict[str, set[int]] = {}
    for part in sorted(data_directory.glob("part-*.json")):
        try:
            payload = json.loads(part.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        for name, lines in payload.items():
            merged.setdefault(name, set()).update(lines)
    return merged


def percentage(covered: int, total: int) -> float:
    return 100.0 if total == 0 else 100.0 * covered / total


def build_report(
    source: Path,
    executed: dict[str, set[int]],
) -> dict[str, object]:
    modules = []
    total_statements = 0
    total_covered = 0
    for path in sorted(source.rglob("*.py")):
        statements = statements_of(path)
        hit = executed.get(str(path.resolve()), set()) & statements
        total_statements += len(statements)
        total_covered += len(hit)
        modules.append(
            {
                "name": str(path.relative_to(source)),
                "statements": len(statements),
                "missing": len(statements) - len(hit),
                "covered_percent": round(percentage(len(hit), len(statements)), 2),
                "missing_lines": sorted(statements - hit),
            }
        )

    slices = []
    slice_path = source / str(SSRF_SLICE["file"])
    if slice_path.is_file():
        names = SSRF_SLICE["definitions"]
        assert isinstance(names, list)
        span = definition_ranges(slice_path, names)
        statements = statements_of(slice_path) & span
        hit = executed.get(str(slice_path.resolve()), set()) & statements
        slices.append(
            {
                "name": SSRF_SLICE["label"],
                "statements": len(statements),
                "missing": len(statements) - len(hit),
                "covered_percent": round(percentage(len(hit), len(statements)), 2),
                "missing_lines": sorted(statements - hit),
            }
        )

    return {
        "modules": modules,
        "slices": slices,
        "total": {
            "statements": total_statements,
            "missing": total_statements - total_covered,
            "covered_percent": round(
                percentage(total_covered, total_statements), 2
            ),
        },
    }


def print_table(report: dict[str, object]) -> None:
    rows: list[tuple[str, object, object, object]] = []
    modules = report["modules"]
    slices = report["slices"]
    assert isinstance(modules, list)
    assert isinstance(slices, list)
    for entry in [*modules, *slices]:
        rows.append(
            (
                str(entry["name"]),
                entry["statements"],
                entry["missing"],
                entry["covered_percent"],
            )
        )
    total = report["total"]
    assert isinstance(total, dict)
    width = max([len("Name"), *(len(row[0]) for row in rows)])
    header = f"{'Name'.ljust(width)}  {'Stmts':>6}  {'Miss':>5}  {'Cover':>7}"
    print(header)
    print("-" * len(header))
    for name, statements, missing, covered in rows:
        print(
            f"{name.ljust(width)}  {statements:>6}  {missing:>5}  {covered:>6.1f}%"
        )
    print("-" * len(header))
    print(
        f"{'TOTAL'.ljust(width)}  {total['statements']:>6}  "
        f"{total['missing']:>5}  {total['covered_percent']:>6.1f}%"
    )


def check_thresholds(report: dict[str, object], total_threshold: float) -> list[str]:
    failures = []
    total = report["total"]
    assert isinstance(total, dict)
    covered = total["covered_percent"]
    assert isinstance(covered, float)
    if covered < total_threshold:
        failures.append(f"total coverage {covered:.1f}% < {total_threshold:.1f}%")

    modules = report["modules"]
    assert isinstance(modules, list)
    for entry in modules:
        threshold = MODULE_THRESHOLDS.get(str(entry["name"]))
        if threshold is None:
            continue
        value = entry["covered_percent"]
        assert isinstance(value, float)
        if value < threshold:
            failures.append(
                f"{entry['name']} coverage {value:.1f}% < {threshold:.1f}% "
                f"(missing lines: {entry['missing_lines']})"
            )

    slices = report["slices"]
    assert isinstance(slices, list)
    for entry in slices:
        threshold = SSRF_SLICE["threshold"]
        assert isinstance(threshold, float)
        value = entry["covered_percent"]
        assert isinstance(value, float)
        if value < threshold:
            failures.append(
                f"{entry['name']} coverage {value:.1f}% < {threshold:.1f}% "
                f"(missing lines: {entry['missing_lines']})"
            )
    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Measure statement coverage of src/noetrail.",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help="package directory to measure (default: src/noetrail)",
    )
    parser.add_argument(
        "--json",
        type=Path,
        default=None,
        help="write the machine-readable report to this path",
    )
    parser.add_argument(
        "--fail-under",
        type=float,
        default=DEFAULT_TOTAL_THRESHOLD,
        help=f"total coverage floor (default: {DEFAULT_TOTAL_THRESHOLD})",
    )
    parser.add_argument(
        "--no-thresholds",
        action="store_true",
        help="report the numbers without failing on them",
    )
    parser.add_argument(
        "command",
        nargs=argparse.REMAINDER,
        help="command to measure (default: the unittest suite)",
    )
    args = parser.parse_args(argv)

    if sysconfig.get_config_var("Py_GIL_DISABLED"):
        # sys.settrace on a free-threaded build does not see other threads
        # reliably; refusing is better than reporting a number that is wrong.
        print(
            "coverage: free-threaded builds are not supported by this tracer",
            file=sys.stderr,
        )
        return 2

    source = args.source.resolve()
    if not source.is_dir():
        parser.error(f"source directory does not exist: {source}")

    command = [item for item in args.command if item != "--"] or DEFAULT_COMMAND

    data_directory = Path(tempfile.mkdtemp(prefix="noetrail-coverage-data-"))
    try:
        suite_status = run_measured(command, source, data_directory)
        executed = merge_parts(data_directory)
        part_count = len(list(data_directory.glob("part-*.json")))
    finally:
        shutil.rmtree(data_directory, ignore_errors=True)

    # A failing command is reported as itself; an empty measurement after a
    # green run means the tracer never attached, which is worse than a gap.
    if suite_status != 0:
        print(
            f"coverage: the measured command failed with status {suite_status}",
            file=sys.stderr,
        )
        return suite_status

    if not executed:
        print(
            "coverage: no measurement was recorded; the tracer did not run",
            file=sys.stderr,
        )
        return 2

    report = build_report(source, executed)
    report["measured_processes"] = part_count
    report["command"] = command
    report["suite_status"] = suite_status

    print_table(report)
    print(f"\nmeasured processes: {part_count}")

    if args.json is not None:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    if args.no_thresholds:
        return 0

    failures = check_thresholds(report, args.fail_under)
    for failure in failures:
        print(f"coverage: {failure}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
